name: Arduino Library CI

on: [pull_request, push, repository_dispatch]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh
    
    - name: Adafruit-GFX-Library
      run: if [ ! -d "$HOME/Arduino/libraries/Adafruit-GFX-Library" ]; then git clone https://github.com/adafruit/Adafruit-GFX-Library.git $HOME/Arduino/libraries/Adafruit-GFX-Library;  fi
      
    - name: NeoPixelBus
      run: if [ ! -d "$HOME/Arduino/libraries/NeoPixelBus" ]; then git clone https://github.com/Makuna/NeoPixelBus.git $HOME/Arduino/libraries/NeoPixelBus; fi

    - name: Adafruit_BusIO
      run: if [ ! -d "$HOME/Arduino/libraries/Adafruit_BusIO" ]; then git clone https://github.com/adafruit/Adafruit_BusIO.git $HOME/Arduino/libraries/Adafruit_BusIO; fi
    
    - name: test platforms
      run: python3 ci/build_platform.py main_platforms

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 